### ISSUE TITLE
I get this when i start the script

### ISSUE THREAD

**Issue by ggauzin** [Orion1125/XRPL-Sniper-Bot#2]
λ    node xrpl.js
D:\GitHub\XRPL-Sniper-Bot\node_modules\xrpl\dist\npm\client\index.js:62
            throw new errors_1.ValidationError('server URI must start with `wss://`, `ws://`, `wss+unix://`, or `ws+unix://`.');
            ^

ValidationError: server URI must start with `wss://`, `ws://`, `wss+unix://`, or `ws+unix://`.
    at new Client (D:\GitHub\XRPL-Sniper-Bot\node_modules\xrpl\dist\npm\client\index.js:62:19)
    at Object.<anonymous> (D:\GitHub\XRPL-Sniper-Bot\xrpl.js:12:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  data: undefined
}

Node.js v20.10.0

**Comment by oriontsx** [comment]
please edit the .env file and put in the wss rpc url for the XRP blockchain
and test again 
thank you

**Comment by ggauzin** [comment]
not workin
